fragment UserParts on User {
  __typename
  users {
    __typename
    username
    name
    email
    password {
      value
      passwordChangeRequired
    }
  }
}

fragment NavBarParts on NavBar {
  __typename
  navbarImage
}

fragment PageParts on Page {
  __typename
  slug
  pageType
  blocks {
    __typename
    ... on PageBlocksHomePageBlock {
      HeadingOfMainBanner
      TextOfMainBanner
      ContactUsButton
      ContactUsButtonLink
      mainFeatureList {
        __typename
        featureheading
        featureImage
        featuredescription
        featureurl
      }
      serviceheading
      servicetext
      serviceslist {
        __typename
        servicesName
        urlForservices
      }
      servicesImage
      designImage
      designheading
      designtext
      designs {
        __typename
        designName
      }
      ourFeatureheading
      ourFeaturetext
      ourfeatureslist {
        __typename
        featureName
        featureDescription
      }
      funfactheading
      funfacttext
      funfactcontactheading
      funfactcontacttext
      funfactcontactarea
      factslist {
        __typename
        factsnumbers
        factsfield
      }
      RecentCaseWorks {
        __typename
        caseHeading
        casetext
        casestudyimage
        slug
      }
    }
    ... on PageBlocksBlogBlock {
      blogpost {
        __typename
        blogimage
        postedon
        headingpro
        postedBy
        duration
        description
        slug
        blogcategory
        blogcategory2
        blogindustry
        blogdepartment
      }
      industriesheading
      industries {
        __typename
        industriesdesc
      }
      deptheading
      departments {
        __typename
        departmentsdesc
      }
      catheading
      categories {
        __typename
        catdesc
      }
    }
    ... on PageBlocksButtonBlock {
      buttonList {
        __typename
        name
        url
      }
    }
    ... on PageBlocksCaseStudiesDetailsBlock {
      title
      image
      body
    }
    ... on PageBlocksCaseStudiesBlock {
      casestudies {
        __typename
        heading
        casedesc
        caseimage
        postedBy
        postedon
        duration
        slug
        casestudytopic
        casestudytopic1
        casestudytopic2
        casestudyindustry
        casestudydepartment
      }
      casestudyindustriesheading
      caseStudyindustries {
        __typename
        casestudydesc
      }
      casestudydeptheading
      casestudydepartments {
        __typename
        casestudydepartmentsdesc
      }
      casestudyptopicheading
      casestudytopic {
        __typename
        casestudytopicdesc
      }
    }
    ... on PageBlocksCookieTypesBlock {
      mainheading
      subheading
      body
    }
    ... on PageBlocksLeftVideoBlock {
      tagline_L_V
      text_L_V
      video_L_V
      url_L_V
      navigation_text_L_V
      list_L_V {
        __typename
        subHeading_L_V
        subContent_L_V
      }
    }
    ... on PageBlocksNewsBlock {
      services {
        __typename
        newsconcept
        newstext
        file
        slug
        postedBy
        postedon
        duration
        newstopic
        newsindustry
        newsdepartment
      }
      newsindustriesheading
      newsindustries {
        __typename
        newsindustriesdesc
      }
      newsdeptheading
      newsdepartments {
        __typename
        newsdepartmentsdesc
      }
      newstopicheading
      newstopics {
        __typename
        newstopicdesc
      }
    }
    ... on PageBlocksPagebannerblock {
      pageTitle
    }
    ... on PageBlocksPolicydefinitionsBlock {
      mainheading
      lastupdated
      body
    }
    ... on PageBlocksRightVideoBlock {
      tagline_R_V
      text_R_V
      video_R_V
      url_R_V
      navigation_text_R_V
      subContent_R_V
      list_R_V {
        __typename
        subHeading_R_V
        keyPointsRI {
          __typename
          keypoint_R_V
        }
      }
    }
    ... on PageBlocksWhitePapersBlock {
      whitepaperslist {
        __typename
        image
        slug
        heading
        postedBy
        postedon
        duration
        description
        whitepapertopic
        whitepapertopic2
        whitepaperindustry
        whitepaperdepartment
      }
      whitepaperindustriesheading
      whitepaperindustries {
        __typename
        whitepaperdesc
      }
      whitepaperdeptheading
      whitepaperdepartments {
        __typename
        whitepaperdepartmentsdesc
      }
      whitepapertopicheading
      whitepapertopic {
        __typename
        whitepapertopicdesc
      }
    }
    ... on PageBlocksWebinarBlock {
      webinars {
        __typename
        webinarConcept
        webinarText
        webinarImage
        postedBy
        postedon
        duration
        slug
        webinartopic
        webinarindustry
        webinardepartment
      }
      webinarindustriesheading
      webinarindustries {
        __typename
        webinardesc
      }
      webinardeptheading
      webinardepartments {
        __typename
        webinardepartmentsdesc
      }
      webinartopicheading
      webinartopic {
        __typename
        webinartopicdesc
      }
    }
  }
}

fragment AllPostsParts on AllPosts {
  __typename
  slug
  pageType
  pagetype
  title
  image
  date
  body
}

fragment WhitepapersParts on Whitepapers {
  __typename
  slug
  pageType
  pagetype
  title
  image
  body
  pdfFileUrl
}

fragment SeoParts on Seo {
  __typename
  path
  title
  description
  canonical
}
