export const ALL_SOLUTIONS = [
  {
    slug: "working-capital-spend-integrity",
    title: "Working Capital & Spend Integrity Program",
    subtitle: "Improve working capital, increase billing and payment accuracy, and strengthen financial execution.",
    icon: "wallet",
    hero: {
      cardLabel: "Working capital",
      cardTitle: "Health overview",
      type: "sparkline",
      tiles: [
        { label: "Billing", icon: "receipt" },
        { label: "Payments", icon: "banknote" },
        { label: "Suppliers", icon: "building" },
      ],
      topChip: { icon: "target", label: "Accuracy", barWidth: "88%" },
      bottomChip: { icon: "alertCircleYellow", label: "Exceptions", value: "Backlog reduced" },
    },
    problemsHeading: "Most organizations believe their financial processes are under control — but in reality:",
    problems: [
      { icon: "receipt", text: "Billing and payments don't always align with agreed terms" },
      { icon: "gitBranch", text: "Invoices, POs, and contracts drift out of sync" },
      { icon: "clock", text: "Payment timing and discount capture are inconsistent" },
      { icon: "refreshCw", text: "Manual reviews and exceptions hide inefficiencies" },
      { icon: "eyeOff", text: "Finance and procurement lack clear visibility into execution gaps" },
    ],
    focusAreasHeading: "Clarity to act on.",
    focusAreas: [
      { icon: "receipt", title: "Billing", description: "Invoice integrity, terms alignment, and accuracy." },
      { icon: "banknote", title: "Payment execution", description: "Timing, discount capture, and disbursement control." },
      { icon: "building", title: "Supplier interactions", description: "Contract alignment and reconciliation discipline." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "lineChart", text: "Clear view of working capital improvement opportunities" },
      { icon: "search", text: "Insights into billing and payment accuracy gaps" },
      { icon: "shieldAlert", text: "Identification of spend integrity and control breakdowns" },
      { icon: "alertCircle", text: "Visibility into exception patterns and inefficiencies" },
      { icon: "listChecks", text: "A prioritized roadmap to improve financial execution" },
    ],
    outcomesHeading: "Performance you can measure.",
    outcomes: [
      { icon: "trendingUp", text: "Improved working capital performance" },
      { icon: "target", text: "Increased billing and payment accuracy" },
      { icon: "shieldCheck", text: "Stronger financial controls and execution discipline" },
      { icon: "zap", text: "Reduced manual effort and exception handling" },
      { icon: "workflow", text: "Clear path to automation and process improvement" },
    ],
    useCases: [
      { icon: "gitBranch", text: "Invoice vs. PO vs. contract misalignment" },
      { icon: "clock", text: "Missed payment discounts and inconsistent payment timing" },
      { icon: "receipt", text: "Supplier billing inconsistencies" },
      { icon: "refreshCw", text: "High volume of manual reviews and exceptions" },
      { icon: "eyeOff", text: "Limited visibility into finance and procurement execution gaps" },
    ],
    howItStartsHeading: "A focused engagement to move from insight to execution.",
    howItStartsSubtitle: "Not just analysis — a working path from assessment to execution.",
    howItStarts: [
      { icon: "search", text: "Assess financial execution gaps" },
      { icon: "barChart", text: "Quantify improvement opportunities" },
      { icon: "map", text: "Define a clear path forward" },
      { icon: "rocket", text: "Implement the solution" },
    ],
    ctaHeading: "Start where execution actually breaks — and fix it.",
    ctaCta: "Start a focused engagement",
  },
  {
    slug: "workflow-automation",
    title: "Workflow Automation",
    subtitle: "Reduce manual work, streamline approvals, and automate document-driven processes.",
    icon: "workflow",
    hero: {
      cardLabel: "Workflow",
      cardTitle: "Automation pipeline",
      type: "steps",
      steps: [
        { label: "Intake", icon: "mail", status: "Auto-classified" },
        { label: "Extract", icon: "fileText", status: "AI parsed" },
        { label: "Route", icon: "gitBranch", status: "Approver matched" },
        { label: "Resolve", icon: "checkCircle", status: "Exception cleared" },
      ],
      topChip: { icon: "clock", label: "Cycle time", barWidth: "72%" },
      bottomChip: { icon: "alertCircleYellow", label: "Exceptions", value: "Auto-triaged" },
    },
    problemsHeading: "Across operations, critical work still depends on manual, document-driven steps:",
    problems: [
      { icon: "mail", text: "Emails, attachments, and manual review drive everyday work" },
      { icon: "fileText", text: "Document interpretation across invoices, contracts, and forms" },
      { icon: "gitBranch", text: "Approval chains and exception handling slow execution" },
      { icon: "network", text: "Tribal knowledge and disconnected systems block flow" },
      { icon: "alertCircle", text: "Critical work still depends on manual touchpoints" },
    ],
    focusAreasHeading: "Clarity to act on.",
    focusAreas: [
      { icon: "workflow", title: "Process redesign", description: "Map manual work and reshape workflows for automation at scale." },
      { icon: "bot", title: "Document & AI automation", description: "Automate document-driven steps with AI where it pays off most." },
      { icon: "zap", title: "Approvals & exceptions", description: "Streamline routing, approvals, and exception handling end-to-end." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "search", text: "Clear identification of manual work and workflow bottlenecks" },
      { icon: "alertCircle", text: "Insights into exception-heavy processes and delays" },
      { icon: "gitBranch", text: "Opportunities to streamline approvals and routing" },
      { icon: "listChecks", text: "Prioritized automation and AI use cases" },
      { icon: "map", text: "A pilot-ready roadmap for workflow automation" },
    ],
    outcomesHeading: "Performance you can measure.",
    outcomes: [
      { icon: "zap", text: "Reduced manual effort across operations" },
      { icon: "clock", text: "Faster turnaround and cycle times" },
      { icon: "trendingDown", text: "Lower operational cost-to-serve" },
      { icon: "shieldCheck", text: "Improved consistency and process control" },
      { icon: "workflow", text: "Scalable, automation-ready workflows" },
    ],
    useCases: [
      { icon: "receipt", text: "Invoice intake and approval workflows" },
      { icon: "fileText", text: "Document-heavy processes (contracts, forms, compliance)" },
      { icon: "mail", text: "Email-driven shared services workflows" },
      { icon: "alertCircle", text: "Exception handling and manual triage" },
      { icon: "network", text: "Workflow gaps between ERP/CRM and real-world operations" },
    ],
    howItStartsHeading: "A structured program to move from insight to execution.",
    howItStartsSubtitle: "From insight to execution — not just analysis.",
    howItStarts: [
      { icon: "search", text: "Identify high-friction workflows" },
      { icon: "listChecks", text: "Define automation opportunities" },
      { icon: "rocket", text: "Move toward pilot implementation" },
    ],
    ctaHeading: "From insight to execution — not just analysis.",
    ctaCta: "Start a focused engagement",
  },
  {
    slug: "decision-ready-data",
    title: "Decision-Ready Data Program",
    subtitle: "Turn fragmented business data into trusted decision support.",
    icon: "barChart",
    hero: {
      cardLabel: "Decision feed",
      cardTitle: "Aligned KPIs",
      type: "kpigrid",
      kpis: [
        { label: "Revenue", value: "On plan", icon: "trendingUp" },
        { label: "Margin", value: "Trusted", icon: "shieldCheck" },
        { label: "Cycle time", value: "Improving", icon: "clock" },
        { label: "Pipeline", value: "Aligned", icon: "gitMerge" },
      ],
      topChip: { icon: "shieldCheck", label: "Trust score", barWidth: "92%" },
      bottomChip: { icon: "fileSpreadsheetYellow", label: "Reconciliation", value: "Effort cut" },
    },
    problemsHeading: "Most organizations have more data than ever — but it doesn't reach decisions:",
    problems: [
      { icon: "shieldAlert", text: "Leadership doesn't trust the numbers" },
      { icon: "gitBranch", text: "KPIs are defined differently across teams" },
      { icon: "clock", text: "Reporting takes too long and requires manual reconciliation" },
      { icon: "eyeOff", text: "Analytics exists, but is not easily usable" },
      { icon: "alertCircle", text: "Decision-making is slower than it should be" },
    ],
    focusAreasHeading: "Clarity to act on.",
    focusAreas: [
      { icon: "gitMerge", title: "Metric alignment", description: "Align KPI definitions and business logic across functions." },
      { icon: "database", title: "Trusted data", description: "Establish a foundation leaders can rely on for every decision." },
      { icon: "barChart", title: "Decision support", description: "Turn aligned signals into clear, actionable insight at the top." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "search", text: "Clear view of KPI inconsistencies and trust gaps" },
      { icon: "alertCircle", text: "Identification of decision friction and reporting bottlenecks" },
      { icon: "gitMerge", text: "Alignment of business logic and metric definitions" },
      { icon: "shieldCheck", text: "Framework for trusted, decision-ready data" },
      { icon: "listChecks", text: "Roadmap for modern analytics and AI enablement" },
    ],
    outcomesHeading: "Performance you can measure.",
    outcomes: [
      { icon: "zap", text: "Faster, more confident decision-making" },
      { icon: "target", text: "Consistent and trusted business metrics" },
      { icon: "trendingDown", text: "Reduced manual reporting and reconciliation effort" },
      { icon: "users", text: "Improved alignment across teams and functions" },
      { icon: "sparkles", text: "Strong foundation for AI and self-service analytics" },
    ],
    useCases: [
      { icon: "gitBranch", text: "Conflicting KPI definitions across departments" },
      { icon: "shieldAlert", text: "Lack of trust in dashboards and reports" },
      { icon: "fileSpreadsheet", text: "Heavy reliance on Excel for reconciliation" },
      { icon: "clock", text: "Slow executive reporting cycles" },
      { icon: "eyeOff", text: "Data available but not usable for decisions" },
    ],
    howItStartsHeading: "A focused engagement to move from data to decisions.",
    howItStartsSubtitle: "From fragmented data to actionable insight.",
    howItStarts: [
      { icon: "search", text: "Assess decision and data friction" },
      { icon: "gitMerge", text: "Align business metrics" },
      { icon: "map", text: "Define a path to decision-ready data" },
    ],
    ctaHeading: "From fragmented data to actionable insight.",
    ctaCta: "Start a focused engagement",
  },
  {
    slug: "employee-knowledge-productivity",
    title: "Employee Knowledge & Productivity",
    subtitle: "Accelerate onboarding and give employees instant, context-aware answers — from day one.",
    icon: "bookOpen",
    hero: {
      cardLabel: "Day 1",
      cardTitle: "New-hire orchestration",
      type: "steps",
      steps: [
        { label: "System access", icon: "keyRound", status: "Provisioned" },
        { label: "Equipment", icon: "laptop", status: "Shipped" },
        { label: "Role guidance", icon: "compass", status: "AI tour ready" },
        { label: "Knowledge agent", icon: "bot", status: "Live · context-aware" },
      ],
      topChip: { icon: "clock", label: "Time to ramp", barWidth: "78%" },
      bottomChip: { icon: "checkCircle", label: "SME tickets", value: "Deflected by agent" },
    },
    problemsHeading: "Onboarding is broken — and day-to-day knowledge is locked in silos:",
    problems: [
      { icon: "userPlus", text: "Onboarding is inconsistent, manual, and dependent on managers or peers" },
      { icon: "keyRound", text: "Access to enterprise systems is delayed, slowing new-hire productivity" },
      { icon: "boxes", text: "Provisioning of tools, systems, and equipment is fragmented across teams" },
      { icon: "folderSearch", text: "Knowledge is scattered across systems, documents, and emails" },
      { icon: "users", text: "Employees rely on specific SMEs for answers — and answers lack context" },
    ],
    focusAreasHeading: "Onboarding and knowledge — under one program.",
    focusAreas: [
      { icon: "userPlus", title: "Onboarding agents", description: "Role-, designation-, and level-driven agents that orchestrate access, tools, and guidance from day one." },
      { icon: "bot", title: "Knowledge agents", description: "Context-aware answers across HR systems, SharePoint, and internal documents — without SME bottlenecks." },
      { icon: "network", title: "Cross-team orchestration", description: "Coordinate IT, HR, and operations so onboarding tasks happen in the right order, every time." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "userPlus", text: "AI-powered onboarding agents driven by role, designation, and level" },
      { icon: "keyRound", text: "Automated provisioning of system access across enterprise platforms" },
      { icon: "laptop", text: "Automated equipment provisioning (e.g. Windows vs. Mac by role/level)" },
      { icon: "compass", text: "Guided navigation across systems, processes, and responsibilities" },
      { icon: "database", text: "Unified, context-aware access to enterprise knowledge and documents" },
      { icon: "map", text: "A roadmap for AI-powered onboarding and knowledge enablement" },
    ],
    outcomesHeading: "Productivity you can measure.",
    outcomes: [
      { icon: "clock", text: "Onboarding time reduced from days/weeks to hours/days" },
      { icon: "zap", text: "Faster system access and immediate Day-1 productivity" },
      { icon: "users", text: "Lower reliance on managers and SMEs for support" },
      { icon: "shieldCheck", text: "Consistent onboarding and training across teams and geographies" },
      { icon: "layers", text: "Scalable onboarding and knowledge access across the organization" },
    ],
    useCases: [
      { icon: "keyRound", text: "Delays in system access for new employees" },
      { icon: "network", text: "Manual coordination between HR, IT, and hiring managers" },
      { icon: "users", text: "Inconsistent onboarding across roles, regions, or business units" },
      { icon: "laptop", text: "Equipment provisioning delays and inconsistencies" },
      { icon: "folderSearch", text: "Employees searching across multiple systems for answers" },
      { icon: "bookOpen", text: "Knowledge locked in documents, emails, and legacy systems" },
    ],
    howItStartsHeading: "A focused engagement to move from gap to pilot agent.",
    howItStartsSubtitle: "Faster ramp-up. Fewer SME tickets. A scalable onboarding and knowledge experience.",
    howItStarts: [
      { icon: "search", text: "Assess onboarding and productivity gaps" },
      { icon: "listChecks", text: "Define AI-driven onboarding and knowledge solutions" },
      { icon: "rocket", text: "Deploy a pilot onboarding and productivity agent" },
    ],
    ctaHeading: "Faster ramp-up. Fewer SME tickets. A scalable onboarding and knowledge experience.",
    ctaCta: "Start a focused engagement",
  },
  {
    slug: "customer-support-optimization",
    title: "Customer Experience & Support Optimization",
    subtitle: "Optimize customer onboarding, support, and experience — at scale. Customers don't care about your ticket queue; they care about fast, accurate answers.",
    icon: "headset",
    hero: {
      cardLabel: "Support inbox",
      cardTitle: "AI triage & resolution",
      type: "steps",
      steps: [
        { label: "Ticket #4821", icon: "messageSquare", status: "Auto-resolved" },
        { label: "Routing", icon: "gitBranch", status: "Tier-2 matched" },
        { label: "Agent assist", icon: "sparkles", status: "Context surfaced" },
        { label: "Onboarding step", icon: "compass", status: "Customer guided" },
      ],
      topChip: { icon: "clock", label: "Resolution time", barWidth: "42%" },
      bottomChip: { icon: "star", label: "CSAT", value: "Trending up" },
    },
    problemsHeading: "Customer-facing operations are fragmented and inefficient:",
    problems: [
      { icon: "messageSquare", text: "Support teams are overwhelmed with repetitive queries" },
      { icon: "clock", text: "Resolution times are longer than expected" },
      { icon: "search", text: "Agents struggle to access the right information quickly" },
      { icon: "trendingUp", text: "Support costs increase without improving experience" },
      { icon: "userPlus", text: "B2B customer onboarding is manual, slow, and inconsistent" },
    ],
    focusAreasHeading: "A cleaner path from query to resolution.",
    focusAreas: [
      { icon: "bot", title: "Support automation", description: "AI agents that resolve repetitive queries and assist agents with context-aware answers." },
      { icon: "compass", title: "Guided onboarding", description: "AI-guided journeys for B2B customer onboarding — accounts, integrations, and workflows." },
      { icon: "gitBranch", title: "Triage & routing", description: "Intelligent ticket classification and routing so the right issue reaches the right team — fast." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "bot", text: "Automation of repetitive customer queries" },
      { icon: "gitBranch", text: "Intelligent ticket triage and routing" },
      { icon: "sparkles", text: "Context-aware assistance for support agents" },
      { icon: "compass", text: "AI-guided customer onboarding journeys" },
      { icon: "database", text: "Faster access to knowledge across systems" },
      { icon: "map", text: "A roadmap for scalable customer-experience optimization" },
    ],
    outcomesHeading: "Lower cost, faster resolution, happier customers.",
    outcomes: [
      { icon: "trendingDown", text: "20–40% reduction in support cost per ticket" },
      { icon: "clock", text: "30–50% faster resolution times" },
      { icon: "messageSquare", text: "25–50% reduction in ticket volume" },
      { icon: "star", text: "10–20 point improvement in NPS / CSAT" },
      { icon: "users", text: "15–30% increase in agent productivity" },
      { icon: "rocket", text: "30–50% faster B2B customer onboarding" },
    ],
    useCases: [
      { icon: "messageSquare", text: "High volume of repetitive support tickets" },
      { icon: "gitBranch", text: "Manual triage and routing of issues" },
      { icon: "search", text: "Agents searching across systems for answers" },
      { icon: "clock", text: "Long resolution times across channels" },
      { icon: "userPlus", text: "B2B customer onboarding across ops, IT, and support" },
      { icon: "settings", text: "Manual setup of customer accounts, integrations, and workflows" },
    ],
    howItStartsHeading: "A focused engagement to move from gaps to a working pilot.",
    howItStartsSubtitle: "Lower cost per ticket. Faster resolution. A scalable customer experience.",
    howItStarts: [
      { icon: "search", text: "Assess customer-facing workflow inefficiencies" },
      { icon: "listChecks", text: "Define an optimization roadmap and AI use cases" },
      { icon: "rocket", text: "Deploy a pilot onboarding and support solution" },
    ],
    ctaHeading: "Lower cost per ticket. Faster resolution. A scalable customer experience.",
    ctaCta: "Start a focused engagement",
  },
  {
    slug: "ai-solution-delivery",
    title: "AI Solution Delivery",
    subtitle: "Turn AI ideas into production-ready, agent-driven workflow solutions — embedded in real operations, not isolated pilots.",
    icon: "rocket",
    hero: {
      cardLabel: "AI delivery",
      cardTitle: "Production pipeline",
      type: "steps",
      steps: [
        { label: "Use case", icon: "lightbulb", status: "Validated" },
        { label: "Agent build", icon: "bot", status: "In progress" },
        { label: "Integration", icon: "network", status: "Connected" },
        { label: "Production", icon: "checkCircle", status: "Live · 6–10 wks" },
      ],
      topChip: { icon: "zap", label: "Deployment", barWidth: "85%" },
      bottomChip: { icon: "trendingUp", label: "Adoption", value: "2–3× target" },
    },
    problemsHeading: "Organizations struggle to identify the right agentic AI use cases — and execution breaks down:",
    problems: [
      { icon: "lightbulb", text: "AI use cases are unclear, overlapping, or too broad" },
      { icon: "gitBranch", text: "Pilots don't connect to real operational workflows" },
      { icon: "users", text: "Adoption fails because solutions aren't embedded in daily work" },
      { icon: "network", text: "Integration with existing systems is underestimated" },
      { icon: "alertCircle", text: "Teams lack the AI delivery skills to take ideas to production" },
    ],
    focusAreasHeading: "From use case to deployed agent.",
    focusAreas: [
      { icon: "target", title: "Use case selection", description: "Identify and prioritize the AI use cases with the highest operational and business impact." },
      { icon: "bot", title: "Agent development", description: "Build production-ready agentic AI solutions embedded in real operational workflows." },
      { icon: "rocket", title: "Deployment & adoption", description: "Deliver solutions in 6–10 weeks — with integration, change management, and adoption built in." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "target", text: "Prioritized AI use cases aligned to operational bottlenecks" },
      { icon: "bot", text: "Production-ready agentic AI solution embedded in real workflows" },
      { icon: "network", text: "Integration with existing enterprise systems" },
      { icon: "users", text: "Change management and user adoption support" },
      { icon: "barChart", text: "Measurable outcomes: 20–40% process efficiency, 2–3× adoption" },
      { icon: "map", text: "A roadmap for scaling AI across the organization" },
    ],
    outcomesHeading: "AI that ships — and gets adopted.",
    outcomes: [
      { icon: "zap", text: "20–40% improvement in process efficiency" },
      { icon: "users", text: "2–3× AI adoption vs. typical pilots" },
      { icon: "clock", text: "6–10 week time to production" },
      { icon: "network", text: "Deep integration with existing systems and workflows" },
      { icon: "layers", text: "Scalable AI delivery model for future use cases" },
    ],
    useCases: [
      { icon: "lightbulb", text: "AI ideas with no clear path to production" },
      { icon: "gitBranch", text: "Pilots that never made it to real operations" },
      { icon: "network", text: "Disconnected AI tools with no workflow integration" },
      { icon: "users", text: "Low adoption of existing AI investments" },
      { icon: "bot", text: "Manual processes where agentic AI can automate execution" },
      { icon: "alertCircle", text: "Lack of in-house AI delivery capability" },
    ],
    howItStartsHeading: "A focused engagement to move from idea to production agent.",
    howItStartsSubtitle: "Not just analysis — an initial production-ready AI solution in 6–10 weeks.",
    howItStarts: [
      { icon: "search", text: "Identify and validate the right AI use cases" },
      { icon: "listChecks", text: "Design and build the production agent" },
      { icon: "rocket", text: "Deploy, integrate, and drive adoption" },
    ],
    ctaHeading: "Move AI from idea to production in 6–10 weeks. 20–40% process efficiency. 2–3× adoption.",
    ctaCta: "Start a focused engagement",
  },
  {
    slug: "ai-risk-cost-governance",
    title: "AI Risk, Cost & Governance",
    subtitle: "Ensure AI is secure, controlled, cost-effective, and scalable — with the visibility, policies, and FinOps to back it up.",
    icon: "shieldCheck",
    hero: {
      cardLabel: "Governance",
      cardTitle: "AI control plane",
      type: "steps",
      steps: [
        { label: "AI inventory", icon: "eye", status: "Mapped" },
        { label: "Policies", icon: "scale", status: "Enforced" },
        { label: "Cost tracking", icon: "dollarSign", status: "On budget" },
        { label: "Risk posture", icon: "shieldCheck", status: "Compliant" },
      ],
      topChip: { icon: "shieldCheck", label: "Risk posture", barWidth: "88%" },
      bottomChip: { icon: "trendingDown", label: "AI spend", value: "Trending down" },
    },
    problemsHeading: "As AI adoption increases, governance often lags behind:",
    problems: [
      { icon: "eyeOff", text: "No clear visibility into where AI is being used" },
      { icon: "shieldAlert", text: "Data exposure and model risks are not fully controlled" },
      { icon: "dollarSign", text: "AI costs are not tracked or optimized" },
      { icon: "fileWarning", text: "Lack of policies, controls, and accountability" },
      { icon: "network", text: "Decentralized adoption leads to inconsistency" },
    ],
    focusAreasHeading: "Visibility, policies, and FinOps in one program.",
    focusAreas: [
      { icon: "eye", title: "Visibility & inventory", description: "Clear view of where AI is used, who owns it, and what risk it carries — across the organization." },
      { icon: "scale", title: "Governance & controls", description: "Frameworks, policies, and accountability so AI is deployed safely, responsibly, and consistently." },
      { icon: "gauge", title: "Cost & FinOps", description: "Cost tracking, attribution, and optimization strategies to keep AI investments under control." },
    ],
    whatYouGetHeading: "What you get from the engagement.",
    whatYouGet: [
      { icon: "eye", text: "Visibility into AI usage, risk, and cost across the organization" },
      { icon: "scale", text: "Framework for AI governance and accountability" },
      { icon: "lock", text: "Policies and controls for secure AI adoption" },
      { icon: "dollarSign", text: "Cost tracking and optimization strategies" },
      { icon: "map", text: "A roadmap for scalable AI governance" },
      { icon: "listChecks", text: "Standardized review and approval workflows for new AI use cases" },
    ],
    outcomesHeading: "Safer, cheaper, more confident AI adoption.",
    outcomes: [
      { icon: "shieldCheck", text: "Reduced risk and improved compliance for AI initiatives" },
      { icon: "trendingDown", text: "Better control over AI-related costs" },
      { icon: "scale", text: "Consistent governance across teams and use cases" },
      { icon: "users", text: "Increased confidence in AI adoption" },
      { icon: "layers", text: "Scalable and sustainable AI operations" },
    ],
    useCases: [
      { icon: "scale", text: "Lack of centralized AI governance" },
      { icon: "network", text: "Uncontrolled use of AI tools across teams" },
      { icon: "shieldAlert", text: "Unclear data security and compliance risks" },
      { icon: "dollarSign", text: "Rising AI costs without visibility" },
      { icon: "fileWarning", text: "No standardized policies for AI usage" },
      { icon: "settings", text: "Inconsistent model and vendor approval across business units" },
    ],
    howItStartsHeading: "A focused engagement to lay the governance foundation.",
    howItStartsSubtitle: "Not just policy — a working control plane for AI usage, risk, and cost.",
    howItStarts: [
      { icon: "search", text: "Assess current AI usage and risk exposure" },
      { icon: "listChecks", text: "Define governance framework, controls, and cost visibility" },
      { icon: "shieldCheck", text: "Implement the governance foundation" },
    ],
    ctaHeading: "Lower risk. Lower cost. AI you can scale with confidence.",
    ctaCta: "Start a focused engagement",
  },
];

export function getSolutionBySlug(slug) {
  return ALL_SOLUTIONS.find((s) => s.slug === slug) || null;
}
